// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxqejxwmgympqegpstbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4cWVqeHdtZ3ltcHFlZ3BzdGJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNDAwNzksImV4cCI6MjA2MTYxNjA3OX0.ue5_2uylMMbvY4agCe1QK3Tcdc-w9eY1OjNTFkFcmGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);