// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzbzcfrklspkhrfgkmcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6YnpjZnJrbHNwa2hyZmdrbWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNDQwMjQsImV4cCI6MjA2MDcyMDAyNH0.fD1RJNo614XRtBhG_9N18UvqHh-tKGOj4D_0W_SM6Mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);